update dictionary set display = 'οἷος, οἵα, οἷον' where lemma = 'οἷος'
update dictionary set display = 'κακοποιός, οῦ, ὁ' where lemma = 'κακοποιός'
update dictionary set display = 'στεῖρα, ας, ἡ' where lemma = 'στεῖρα'
update dictionary set display = 'ἄρτιος, ία, ον' where lemma = 'ἄρτιος'
update dictionary set display = 'βαλλάντιον, ου, τό' where lemma = 'βαλλάντιον'
update dictionary set display = 'πετεινός, ή, όν' where lemma = 'πετεινόν'
update dictionary set display = 'λαλιά, ᾶς, ἡ' where lemma = 'λαλιά'
update dictionary set display = 'καταλαλιά, ᾶς, ἡ' where lemma = 'καταλαλιά'
update dictionary set display = 'ὠτάριον, ου, τό' where lemma = 'ὠτάριον'
update dictionary set display = 'ἄλφα, τό' where lemma = 'ἄλφα'
update dictionary set display = 'ἐπαρχεία, ας, ἡ' where lemma = 'ἐπαρχεία'
update dictionary set display = 'ἐμπαιγμονή, ῆς, ἡ' where lemma = 'ἐμπαιγμονή'
update dictionary set display = 'ἄμωμον, ου, τό' where lemma = 'ἄμωμον'
update dictionary set display = 'ἀφθορία, ας, ἡ' where lemma = 'ἀφθορία'
update dictionary set display = 'φάρμακον, ου, τό', gloss = 'a drug, medicine' where lemma = 'φάρμακον'
update dictionary set display = 'σφυδρόν, οῦ, τό', gloss = 'the ankle' where lemma = 'σφυδρόν'
update dictionary set display = 'στασιαστής, ,οῦ, ὁ' where lemma = 'στασιαστής'
update dictionary set display = 'σπίλος, ου, ὁ' where lemma = 'σπίλος'
update dictionary set display = 'σιτίον, ου, τό' where lemma = 'σιτίον'
update dictionary set display = 'σίκερα, ερος, τό' where lemma = 'σίκερα'
update dictionary set display = 'πρῷρα, ας, ἡ' where lemma = 'πρῷρα'
update dictionary set display = 'πλόος, οῦς, ὁ' where lemma = 'πλόος'
update dictionary set display = 'πάγος, ου, ὁ' where lemma = 'πάγος'
update dictionary set display = 'λογεία, ας, ἡ' where lemma = 'λογεία'
update dictionary set display = 'κλινάριον, ου, τό' where lemma = 'κλινάριον'
update dictionary set display = 'κυλισμός, οῦ, ὁ' where lemma = 'κυλισμός'
update dictionary set display = 'κιννάμωμον, ου, τό' where lemma = 'κιννάμωμον'
update dictionary set display = 'καταδίκη, ης, ἡ' where lemma = 'καταδίκη'
update dictionary set display = 'εἰδωλολατρία, ας, ἡ' where lemma = 'εἰδωλολατρία'
update dictionary set display = 'δοκιμασία, ας, ἡ' where lemma = 'δοκιμασία'
update dictionary set display = 'διαπαρατριβή, ῆς, ἡ' where lemma = 'διαπαρατριβή'
update dictionary set display = 'δεξιολάβος, ου, ὁ' where lemma = 'δεξιολάβος'
update dictionary set display = 'βιβλαρίδιον, ου, τό' where lemma = 'βιβλαρίδιον'
update dictionary set display = 'βελόνη, ης, ἡ' where lemma = 'βελόνη'
update dictionary set display = 'συγκοινωνός, οῦ, ὁ, ἡ' where lemma = 'συγκοινωνός'
update dictionary set display = 'Συντύχη, ης, ἡ' where lemma = 'Συντύχη'
update dictionary set display = 'Κολοσσαί, ῶν, ἡ' where lemma = 'Κολοσσαί'
update dictionary set display = 'μυρίοι, αι, α' where lemma = 'μυρίοι'
update dictionary set display = 'ζώνη, ης, ἡ' where lemma = 'ζώνη'
update dictionary set display = 'λαλιά, ᾶς, ἡ' where lemma = 'λαλιά'
update dictionary set display = 'διαφθορά, ᾶς, ἡ' where lemma = 'διαφθορά'
update dictionary set display = 'καύσων, ωνος, ὁ' where lemma = 'καύσων'
update dictionary set display = 'Ζεύς, Διός, ὁ' where lemma = 'Ζεύς'
update dictionary set display = 'ἅρπαξ (αγος), αγον' where lemma = 'ἅρπαξ'

update dictionary set gloss = 'having three rows<cr>ὁ τρίστεγος - the third story of a building' where lemma = 'τρίστεγος'
update dictionary set gloss = '(μή + γε - always part of expression "εί δὲ μήγε") but if not, otherwise' where lemma = 'μήγε'
update dictionary set gloss = 'I meet with, talk with, make a petition (to someone)' where lemma = 'ἐντυγχάνω'
update dictionary set gloss = 'I swear falsely' where lemma = 'ἐπιορκέω'
update dictionary set gloss = 'I press together, confine, compel<cr>συνέχομαι - I am afflicted with' where lemma = 'συνέχω'
update dictionary set gloss = 'a foundation', display = 'θεμέλιος, ου, ὁ' where lemma = 'θεμέλιος'
update dictionary set gloss = 'pagan, heathen, gentile<cr>ὁ ἐθνικός - a Gentile, non-Jew' where lemma = 'ἐθνικός'
update dictionary set gloss = 'deep' where lemma = 'βαθύς'
update dictionary set gloss = 'fifth' where lemma = 'πέμπτος'
update dictionary set gloss = 'foreign<cr>ὁ πάροικος - a foreigner, a sojouner' where lemma = 'πάροικος'
update dictionary set gloss = 'Roman province "Asia" (roughly the western third of Asia Minor)' where lemma = 'Ἀσία'
update dictionary set gloss = 'wholly, altogether, at all' where lemma = 'ὅλως'
update dictionary set gloss = 'being an heir with, participating<cr>ὁ συγκληρονόμος - a joint heir' where lemma = 'συγκληρονόμος'
update dictionary set gloss = 'dry, withered<cr>ὁ ξηρός - dry land' where lemma = 'ξηρός'
update dictionary set gloss = 'produce, fruit (of the earth)' where lemma = 'γένημα'
update dictionary set gloss = 'Roman<cr>ὁ Ῥωμαῖος - a Roman citizen' where lemma = 'Ῥωμαῖος'
update dictionary set gloss = '(κατά + ὅτι) in as much as' where lemma = 'καθότι'
update dictionary set gloss = 'rule, regulation; province' where lemma = 'κανών'
update dictionary set gloss = 'I lend<cr>δανείζομαι - borrow' where lemma = 'δανείζω'
update dictionary set gloss = 'I trouble, annoy' where lemma = 'σκύλλω'
update dictionary set gloss = 'somewhere (enclitic)' where lemma = 'πού'
update dictionary set gloss = 'I mistreat, injure' where lemma = 'κακουχέω'
update dictionary set gloss = 'a standing, a place; rebellion, strife' where lemma = 'στάσις'
update dictionary set gloss = 'concerning the law, learned in the Law<cr>ὁ νομικός - a lawyer' where lemma = 'νομικός'
update dictionary set gloss = 'an unmarried person' where lemma = 'ἄγαμος'
update dictionary set gloss = 'a bramble bush', count = 5 where lemma = 'βάτος'
update dictionary set gloss = 'a step, a pace; a raised platform' where lemma = 'βῆμα'
update dictionary set gloss = 'I strike, cut<cr>κόπτομαι - I mourn' where lemma = 'κόπτω'
update dictionary set gloss = 'respectable, elegant' where lemma = 'εὐσχήμων'
update dictionary set gloss = 'respectability, elegantness' where lemma = 'εὐσχημοσύνη'
update dictionary set gloss = 'respectably, elegantly' where lemma = 'εὐσχημόνως'
update dictionary set gloss = 'Lydda' where lemma = 'Λύδδα'
update dictionary set gloss = 'I am estranged, alienated' where lemma = 'ἀπαλλοτριόομαι'
update dictionary set gloss = 'sown<cr>ὁ σπόριμος - a sown field' where lemma = 'σπόριμος'
update dictionary set gloss = 'honorable, worthy of respect' where lemma = 'σεμνός'
update dictionary set gloss = 'Egyptian<cr>ὁ Αἰγύπτιος - the Egyptian' where lemma = 'Αἰγύπτιος'
update dictionary set gloss = 'I shut, close' where lemma = 'φράσσω'
update dictionary set gloss = '(time) passes' where lemma = 'διαγίνομαι'
update dictionary set gloss = '(gen) before, in the presence of, in the eyes of' where lemma = 'ἐναντίον'
update dictionary set gloss = '(gen) over against, opposite, in view of, in the presence of' where lemma = 'ἀπέναντι'

insert into dictionary(lemma,pos,lookup,display,gloss,count) values('βάτος2','noun','βατοσ','βάτος, ου, ὁ','a bath, a (Hebrew) liquid measure between eight and nine gallons',1)

insert into vocab(listid,listnum,lemma) values(9,4,'ὁδός')

update verses set normtext = replace(normtext,'βάτος','βάτος2') where num = 3 and chapter = 16 and verse = 6

update entries set lemma = 'βάτος2' where wordid = 42543

update search set lemma = 'βάτος2' where lookup = 'βατουσ'

update verbparts set parts = 'τυγχάνω, -, ἔτυχον, τέτυχα, -, -' where lemma = 'τυγχάνω'
update verbparts set parts = 'καταλαμβάνω, -, κατέλαβον, -, κατείληπμαι, κατελήμφθην/κατελήφθην' where lemma = 'καταλαμβάνω'
update verbparts set parts = 'διακρίνω (διέκρινον), -, διἐκρινα, -, -, διεκρίθην' where lemma = 'διακρίνω'
update verbparts set parts = 'θέλω (ἤθελον), -, ἠθέλησα, -, -, -' where lemma = 'θέλω'
update verbparts set parts = 'συμφέρω, -, συνήνεγκα, -, -, -' where lemma = 'συμφέρω'

delete from settings where name = 'bookmark'
insert into settings(name,value) values('scrollbtn_blend','50')
insert into settings(name,value) values('vocab_interval','180')
