update dictionary set gloss = 'I put to death' where lemma = 'νεκρόω'
update dictionary set gloss = 'blameless, not causing offence' where lemma = 'ἀπρόσκοπος'
update dictionary set gloss = 'a command, order' where lemma = 'ἔνταλμα'
update dictionary set gloss = 'a command, order' where lemma = 'ἐντολή'
update dictionary set gloss = 'I stain, defile' where lemma = 'μολύνω'
update dictionary set gloss = 'I am glad, rejoice, celebrate' where lemma = 'εὐφραίνω'
update dictionary set gloss = 'inward thought' where lemma = 'ἐνθύμησις'
update dictionary set gloss = 'profane, worldly, worthless' where lemma = 'βέβηλος'
update dictionary set gloss = 'a footstep' where lemma = 'ἴχνος'
update dictionary set display = 'οἰκιακός, οῦ, ὁ', gloss = 'a household member' where lemma = 'οἰκιακός'
update dictionary set gloss = 'I turn away' where lemma = 'ἐκκλίνω'
update dictionary set display = 'ἐλεημοσύνη, ης, ἡ' where lemma = 'ἐλεημοσύνη'
update dictionary set display = 'ἐλεγμός, οῦ, ὁ' where lemma = 'ἐλεγμός'
update dictionary set display = 'Εὐνίκη, ης, ἡ' where lemma = 'Εὐνίκη'
update dictionary set display = 'προσφορά, ᾶς, ἡ' where lemma = 'προσφορά'
update dictionary set display = 'λειτουργός, οῦ, ὁ' where lemma = 'λειτουργός'
update dictionary set display = 'Λύδδα, ης, ἡ' where lemma = 'Λύδδα'
update dictionary set display = 'Ζηνᾶς, ᾶ, ὁ' where lemma = 'Ζηνᾶς'
update dictionary set display = 'Κεγχρεαί, ῶν, αἱ' where lemma = 'Κεγχρεαί'
update dictionary set display = 'βοτάνη, ης, ἡ' where lemma = 'βοτάνη'
update dictionary set display = 'καλάμη, ης, ἡ' where lemma = 'καλάμη'
update dictionary set display = 'δεῖν, δεῖνος, ὁ', gloss = 'someone or other' where lemma = 'δεῖνα'
update dictionary set display = 'εὐσχημοσύνη, ης, ἡ' where lemma = 'εὐσχημοσύνη'
update dictionary set display = 'θήκη, ης, ἡ' where lemma = 'θήκη'
update dictionary set display = 'λήθη, ης, ἡ' where lemma = 'λήθη'
update dictionary set display = 'σίκερον, ου, τό', gloss = 'strong drink' where lemma = 'σίκερα'
update dictionary set display = 'ἀκροθίνιον, ου, τό' where lemma = 'ἀκροθίνιον'
update dictionary set display = 'ἀσσάριον, ου, τό' where lemma = 'ἀσσάριον'
update dictionary set display = 'ἀφροσύνη, ης, ἡ', gloss = 'foolishness' where lemma = 'ἀφροσύνη'
update dictionary set display = 'ἐγκαίνια, ων, τά', gloss = 'the feast of dedication' where lemma = 'ἐγκαίνια'
update dictionary set display = 'κεντυρίων, ωνος, ὁ' where lemma = 'κεντυρίων'
update dictionary set gloss = 'an escort' where lemma = 'ἀπάντησις'
update dictionary set gloss = 'I go around, make a circuit' where lemma = 'περιέρχομαι'
update dictionary set display = 'ὅσιος, α, ον' where lemma = 'ὅσιος'
update dictionary set display = 'ἑδραῖος, α, ον' where lemma = 'ἑδραῖος'
update dictionary set gloss = 'I press or crush together' where lemma = 'στενοχωρέω'
update dictionary set display = 'πλοῦς, πλοός, ὁ' where lemma = 'πλόος'
update dictionary set gloss = 'lazy, troublesome' where lemma = 'ὀκνηρός'
update dictionary set gloss = 'a division, a distinction' where lemma = 'διαίρεσις'
update dictionary set gloss = 'I hold within (metaph - I hold a grudge)<cr>ἐνέχομαι - I am entangled' where lemma = 'ἐνέχω'
update dictionary set gloss = 'I annul, cancel' where lemma = 'ἀκυρόω'
update dictionary set gloss = 'a deposit, earnest-money' where lemma = 'ἀρραβών'
update dictionary set gloss = 'I suffer the pain of childbirth' where lemma = 'ὠδίνω'
update dictionary set gloss = 'a breast' where lemma = 'μαστός'
update dictionary set gloss = 'residing temporarily<cr>ὁ παρεπίδημος - a temporary resident' where lemma = 'παρεπίδημος'
update dictionary set gloss = 'I look carefully; I take heed' where lemma = 'σκοπέω'
update dictionary set gloss = 'I touch; I search for by feeling around' where lemma = 'ψηλαφάω'
update dictionary set display = 'μέλας, αίνα, αν' where lemma = 'μέλας'
update dictionary set gloss = 'I come upon, come after<cr>τῇ ἐπιούσῃ - the following (day)' where lemma = 'ἔπειμι'
update dictionary set gloss = '"you have forsaken me" (in Aramaic)' where lemma = 'σαβαχθάνι'
update dictionary set gloss = 'I am unable; it is impossible' where lemma = 'ἀδυνατέω'
update dictionary set gloss = 'I am glorified' where lemma = 'ἐνδοξάζομαι'
update dictionary set gloss = '"be opened" (in Aramaic)' where lemma = 'ἐφφαθά'
update dictionary set gloss = 'there is' where lemma = 'ἔνι'
update dictionary set gloss = 'I boast proudly' where lemma = 'αὐχέω'
update dictionary set gloss = 'I give a daughter in marriage' where lemma = 'γαμίζω'
update dictionary set gloss = 'I purge thoroughly' where lemma = 'διακαθαίρω'
update dictionary set gloss = 'I keep safe (through danger); I heal' where lemma = 'διασῴζω'
update dictionary set gloss = 'I deceive' where lemma = 'διαχλευάζω'
update dictionary set gloss = 'I consider, reflect' where lemma = 'διενθυμέομαι'
update dictionary set gloss = 'I defame, slander' where lemma = 'δυσφημέω'
update dictionary set gloss = 'I invite in' where lemma = 'εἰσκαλέω'
update dictionary set gloss = 'I emasculate, castrate' where lemma = 'εὐνουχίζω'
update dictionary set gloss = 'I lend' where lemma = 'κίχρημι'
update dictionary set gloss = 'I become tarnished' where lemma = 'κατιόομαι'
update dictionary set gloss = 'I settle, establish' where lemma = 'κατοικίζω'
update dictionary set gloss = 'I muzzle' where lemma = 'κημόω'
update dictionary set display = 'κοῦμ', lookup = 'κουμ', gloss = '"get up!" (in Aramaic)' where lemma = 'κοῦμι'
update dictionary set gloss = 'I surround' where lemma = 'κυκλεύω'
update dictionary set gloss = 'I burst open' where lemma = 'λακάω'
update dictionary set gloss = 'I chew' where lemma = 'μασάομαι'
update dictionary set gloss = 'I overthrow' where lemma = 'μετατρέπω'
update dictionary set gloss = 'I have pity' where lemma = 'οἰκτίρω'
update dictionary set gloss = 'I expose myself to danger' where lemma = 'παραβολεύομαι'
update dictionary set gloss = 'I wait, attend upon' where lemma = 'παρεδρεύω'
update dictionary set gloss = 'I put in beside' where lemma = 'παρεμβάλλω'
update dictionary set gloss = 'I light (a fire)' where lemma = 'περιάπτω'
update dictionary set gloss = 'I remain, survive' where lemma = 'περιλείπομαι'
update dictionary set gloss = 'I call forth' where lemma = 'προκαλέω'
update dictionary set gloss = 'I lean against; I join (a party of people)' where lemma = 'προσκλίνω'
update dictionary set gloss = 'I am frightened' where lemma = 'πτύρομαι'
update dictionary set gloss = 'I endure adversity with' where lemma = 'συγκακουχέομαι'
update dictionary set gloss = 'I am conformed to' where lemma = 'συμμορφίζομαι'
update dictionary set gloss = 'I fall together' where lemma = 'συμπίπτω'
update dictionary set gloss = 'I reconcile' where lemma = 'συναλλάσσω'
update dictionary set gloss = 'I join in entreating' where lemma = 'συνδέομαι'
update dictionary set gloss = 'I set as watchers or guards' where lemma = 'συνεφίστημι'
update dictionary set gloss = 'I see (and understand), realize' where lemma = 'συνοράω'
update dictionary set gloss = 'I bear a message' where lemma = 'ἀγγέλλω'
update dictionary set gloss = 'I gather together, assemble' where lemma = 'ἀθροίζω'
update dictionary set gloss = 'I clothe' where lemma = 'ἀμφιάζω'
update dictionary set gloss = 'I throw (something) around (something)' where lemma = 'ἀμφιβάλλω'
update dictionary set gloss = 'I leap up, start up' where lemma = 'ἀναπηδάω'
update dictionary set gloss = 'I am driven by the wind' where lemma = 'ἀνεμίζομαι'
update dictionary set gloss = 'I come too late; I withhold' where lemma = 'ἀφυστερέω'
update dictionary set gloss = 'I pride myself on' where lemma = 'ἐγκαυχάομαι'
update dictionary set gloss = 'I step out of, step off from' where lemma = 'ἐκβαίνω'
update dictionary set gloss = 'I am hanging (onto something)' where lemma = 'ἐκκρέμαμαι'
update dictionary set gloss = 'I completely escape notice'  where lemma = 'ἐκλανθάνω'
update dictionary set gloss = 'I leap out' where lemma = 'ἐκπηδάω'
update dictionary set gloss = 'I fill quite full' where lemma = 'ἐμπίμπλημι'
update dictionary set gloss = 'I destroy completely' where lemma = 'ἐξολεθρεύω'
update dictionary set gloss = 'I remind again' where lemma = 'ἐπαναμιμνῄσκω'
update dictionary set gloss = 'I come in besides' where lemma = 'ἐπεισέρχομαι'
update dictionary set gloss = 'I bring ships to shore' where lemma = 'ἐπικέλλω'
update dictionary set gloss = 'I lick' where lemma = 'ἐπιλείχω'
update dictionary set gloss = 'I get ready' where lemma = 'ἐπισκευάζω'
update dictionary set gloss = 'I drag upon' where lemma = 'ἐπισπάω'
update dictionary set gloss = 'I sow with seed' where lemma = 'ἐπισπείρω'
update dictionary set gloss = 'I shine out' where lemma = 'ἐπιφαύσκω'
update dictionary set gloss = 'I overlook' where lemma = 'ὑπεροράω'
update dictionary set gloss = 'I cause to go (causal of βαίνω - only appears in compounds in the NT)' where lemma = 'βιβάζω'
update dictionary set gloss = '"Sons of Thunder" (in Aramaic)' where lemma = 'Βοανηργές'
update dictionary set gloss = '"my God" (in Aramaic)' where lemma = 'ἐλωΐ'
update dictionary set gloss = 'the Hebrew or Aramaic language' where lemma = 'Ἑβραΐς'
update dictionary set gloss = '"my God" (in Hebrew); Eli' where lemma = 'ἠλί'
update dictionary set gloss = 'an example, a pattern' where lemma = 'ὑπόδειγμα'
update dictionary set gloss = 'I strive eagerly, I aspire to' where lemma = 'φιλοτιμέομαι'
update dictionary set gloss = '(gen) before, in the sight of' where lemma = 'ἐναντίον'
update dictionary set gloss = 'I throw off, throw away' where lemma = 'ἀποβάλλω'
update dictionary set gloss = 'it is fitting, proper' where lemma = 'ἀνήκω'
update dictionary set display = 'ἄγριος, α, ον' where lemma = 'ἄγριος'
update dictionary set gloss = 'I strengthen' where lemma = 'ἐπιστηρίζω'
update dictionary set gloss = 'I carry around' where lemma = 'περιφέρω'
update dictionary set gloss = 'a worn path (for walking)' where lemma = 'τρίβος'
update dictionary set display = 'αἰσχροκερδής, ές' where lemma = 'αἰσχροκερδής'
update dictionary set gloss = 'I appoint, ordain, declare' where lemma = 'ὁρίζω'
update dictionary set gloss = 'a mark, form, pattern, model' where lemma = 'τύπος'
update dictionary set gloss = 'a female slave, maidservant' where lemma = 'δούλη'
update dictionary set gloss = 'I change, exchange' where lemma = 'ἀλλάσσω'
update dictionary set gloss = 'I make desolate, lay waste' where lemma = 'ἐρημόω'
update dictionary set gloss = 'a courtyard, a residence' where lemma = 'αὐλή'
update dictionary set gloss = '(gen) before' where lemma = 'κατενώπιον'
update dictionary set gloss = 'the stomach<cr>ἐν γαστρί - to be pregnant' where lemma = 'γαστήρ'
update dictionary set gloss = '"little girl" (in Aramaic)' where lemma = 'ταλιθά'
update dictionary set gloss = 'a disappearance' where lemma = 'ἀφανισμός'
update dictionary set gloss = 'hidden, invisible' where lemma = 'ἄφαντος'
update dictionary set gloss = 'I rule as a tetrarch' where lemma = 'τετρααρχέω'
update dictionary set gloss = 'very, very much; exceedingly' where lemma = 'λίαν'
update dictionary set gloss = 'I look (favorably) on' where lemma = 'ἐπιβλέπω'
update dictionary set gloss = 'the roof of a house' where lemma = 'δῶμα'

update dictionary set lemma = 'ἐπαθροίζω', lookup = 'επαθροιζω', display = 'ἐπαθροίζω', gloss = 'I gather together, assemble' where lemma = 'ἐπαθροίζομαι'
update search set lemma = 'ἐπαθροίζω' where lemma = 'ἐπαθροίζομαι'
update search set lookup = 'επαθροιζω' where lookup = 'επαθροιζομαι'
update entries set lemma = 'ἐπαθροίζω' where lemma = 'ἐπαθροίζομαι'
update ntverbforms set lemma = 'ἐπαθροίζω' where lemma = 'ἐπαθροίζομαι'
update verses set normtext = replace(normtext,'ἐπαθροίζομαι','ἐπαθροίζω') where num = 3 and chapter = 11 and verse = 29

insert or ignore into dictionary(lemma,pos,lookup,display,gloss,count,lemmaID) values('οἰκετεία','noun','οικετεια','οἰκετεία, ας, ἡ','all the slaves in a household',1,5420)
update dictionary set count = 3 where lemma = 'οἰκεῖος'
update entries set lemma = 'οἰκετεία' where wordID = 14905
update verses set normtext = replace(normtext,'οἰκεῖος','οἰκετεία') where num = 1 and chapter = 24 and verse = 45
update search set lemma = 'οἰκετεία' where lookup = 'οικετειασ'

insert or ignore into dictionary(lemma,pos,lookup,display,gloss,count,lemmaID) values('Ἀδμίν','noun','αδμιν','Ἀδμίν, ὁ','Admin',1,5421)
update dictionary set count = 2 where lemma = 'Ἀράμ'
update entries set lemma = 'Ἀδμίν' where wordID = 32181
update verses set normtext = replace(normtext,'Ἀράμ','Ἀδμίν') where num = 3 and chapter = 3 and verse = 33
update search set lemma = 'Ἀδμίν' where lookup = 'αδμιν'

insert or ignore into settings(name,value) values('noun_numlines',25)
insert or ignore into settings(name,value) values('noun_lowerrange',30)
insert or ignore into settings(name,value) values('help_text_size',18)

update vocabchildlists set listname = replace(listname,'BeginningGreek','Beginning Greek')
update vocabchildlists set listname = replace(listname,'GoingDeeper','Going Deeper')
