insert or ignore into settings(name,value) values('noun_review','000')
insert or ignore into settings(name,value) values('verb_review','11000000000000000')

update dictionary set gloss = 'with difficulty' where lemma = 'δυσκόλως'
update dictionary set gloss = 'with difficulty, hardly' where lemma = 'μόγις'
update dictionary set gloss = 'a deposit, earnest-money' where lemma = 'ἀρραβών'
update dictionary set gloss = 'I present; I stand alongside' where lemma = 'παρίστημι'
update dictionary set gloss = 'I stand near;(something) is about to happen' where lemma = 'ἐφίστημι'
update dictionary set gloss = 'not made by hand' where lemma = 'ἀχειροποίητος'
update dictionary set gloss = '(adv) if not, unless<cr>(particle) introduces a question expecting a negative response' where lemma = 'μήτι'
update dictionary set gloss = 'stomach, belly, womb' where lemma = 'κοιλία'
update dictionary set gloss = 'poison, corrosion' where lemma = 'ἰός'
update dictionary set gloss = 'condemnation' where lemma = 'κατάκριμα'
update dictionary set gloss = 'a law-court, a tribunal' where lemma = 'κριτήριον'
update dictionary set gloss = '(κατά + ὅτι) because; to the degree that' where lemma = 'καθότι'
update dictionary set gloss = 'I overturn, upset, ruin' where lemma = 'ἀνατρέπω'
update dictionary set gloss = 'I do, act, practice' where lemma = 'πράσσω'
update dictionary set gloss = 'I recline, especially at a dinner-table' where lemma = 'ἀνακλίνω'
update dictionary set gloss = 'rebellion, strife; standing' where lemma = 'στάσις'
update dictionary set gloss = 'a word, speech, reason' where lemma = 'λόγος'
update dictionary set gloss = 'I nurse (a baby)' where lemma = 'θηλάζω'
update dictionary set gloss = 'trembling with fear' where lemma = 'ἔντρομος'
update dictionary set gloss = 'a purpose; the show-bread' where lemma = 'πρόθεσις'
update dictionary set gloss = 'a gate, gateway' where lemma = 'πυλών'
update dictionary set gloss = 'I make (someone) recline (at a table for a meal)' where lemma = 'κατακλίνω'
update dictionary set gloss = 'I recline (at a table for a meal)' where lemma = 'ἀνάκειμαι'
update dictionary set gloss = 'I recline (at a table for a meal)' where lemma = 'ἀνακλίνω'
update dictionary set gloss = 'I depart, withdraw' where lemma = 'ἀναχωρέω'
update dictionary set gloss = 'I deliberate' where lemma = 'συμβάλλω'
update dictionary set gloss = 'I explain; I put a child outside (to die from exposure)' where lemma = 'ἐκτίθημι'
update dictionary set gloss = 'I explain; I am very pleased; I am determined' where lemma = 'εὐδοκέω'
update dictionary set gloss = 'a command, an imposition' where lemma = 'ἐπιταγή'
update dictionary set gloss = 'hard work, pain' where lemma = 'πόνος'
update dictionary set gloss = 'I place in; I am present, (something) happens' where lemma = 'ἐνίστημι'
update dictionary set gloss = 'I stand near; (something) is about to happen' where lemma = 'ἐφίστημι'
update dictionary set gloss = 'I compare, interpret' where lemma = 'συγκρίνω'
update dictionary set gloss = 'I stumble' where lemma = 'πταίω'
update dictionary set gloss = 'I set before<cr>παρατίθεμαι - I entrust' where lemma = 'παρατίθημι'
update dictionary set gloss = 'a hypocrite, pretender' where lemma = 'ὑποκριτής'
update dictionary set gloss = 'hypocrisy, pretending' where lemma = 'ὑπόκρισις'
update dictionary set gloss = 'dipping (in water), washing; baptism' where lemma = 'βαπτισμός'
update dictionary set display = 'συνίστημι/συνιστάνω', gloss = 'I stand together, demonstrate; I commend' where lemma = 'συνίστημι'
update dictionary set gloss = 'I teach, instruct (verbally)' where lemma = 'κατηχέω'
update dictionary set gloss = 'I permit, allow; I let go, release' where lemma = 'ἐάω'
update dictionary set gloss = 'I sprout, bud, grow' where lemma = 'βλαστάνω'
update dictionary set gloss = '(κατά + ὅ) in so far as, with respect to' where lemma = 'καθό'
update dictionary set display = 'μάταιος, α, ον', gloss = 'vain, empty, useless' where lemma = 'μάταιος'
update dictionary set gloss = 'I weave' where lemma = 'πλέκω'
update dictionary set display = 'Γαλιλαῖος, α, ον' where lemma = 'Γαλιλαῖος'
update dictionary set display = 'Σιδώνιος, α, ον' where lemma = 'Σιδώνιος'
update dictionary set display = 'Χαναναῖος, α, ον' where lemma = 'Χαναναῖος'
update dictionary set display = 'αἰώνιος, α, ον' where lemma = 'αἰώνιος'
update dictionary set display = 'δίκαιος, α, ον' where lemma = 'δίκαιος'
update dictionary set display = 'δευτεραῖος, α, ον' where lemma = 'δευτεραῖος'
update dictionary set display = 'δόλιος, α, ον' where lemma = 'δόλιος'
update dictionary set display = 'κόσμιος, α, ον' where lemma = 'κόσμιος'
update dictionary set display = 'μεγαλεῖος, α, ον' where lemma = 'μεγαλεῖος'
update dictionary set display = 'παραθαλάσσιος, α, ον' where lemma = 'παραθαλάσσιος'
update dictionary set display = 'σιδήρεος, α, ον' where lemma = 'σιδήρεος'
update dictionary set display = 'ταλαντιαῖος, α, ον' where lemma = 'ταλαντιαῖος'
update dictionary set display = 'τεταρταῖος, α, ον' where lemma = 'τεταρταῖος'
update dictionary set display = 'ἀλλότριος, α, ον' where lemma = 'ἀλλότριος'
update dictionary set display = 'ἀρχαῖος, α, ον' where lemma = 'ἀρχαῖος'
update dictionary set display = 'ἄξιος, α, ον' where lemma = 'ἄξιος'
update dictionary set display = 'ἄρτιος, α, ον' where lemma = 'ἄρτιος'
update dictionary set display = 'ἅγιος, α, ον' where lemma = 'ἅγιος'
update dictionary set display = 'ἐντόπιος, α, ον' where lemma = 'ἐντόπιος'
update dictionary set display = 'ἑκούσιος, α, ον' where lemma = 'ἑκούσιος'
update dictionary set display = 'Ἰουδαῖος, α, ον' where lemma = 'Ἰουδαῖος'
update dictionary set display = 'ὅμοιος, α, ον' where lemma = 'ὅμοιος'
update dictionary set display = 'ὡραῖος, α, ον' where lemma = 'ὡραῖος'
update dictionary set display = 'ὁποῖος, α, ον' where lemma = 'ὁποῖος'
update dictionary set display = 'οἷος, α, ον' where lemma = 'οἷος'
