update dictionary set gloss = 'I entertain a stranger; I am surpised (by something "strange/ξένος")' where lemma = 'ξενίζω'
update dictionary set gloss = 'new, novel, strange<cr>ὁ ξένος - a foreigner' where lemma = 'ξένος'
update dictionary set gloss = 'I equip/prepare fully; I build, make' where lemma = 'κατασκευάζω'
update dictionary set gloss = 'I put around; I clothe' where lemma = 'περιτίθημι'
update dictionary set gloss = 'rest, relief; freedom' where lemma = 'ἄνεσις'
update dictionary set gloss = 'I fall off, fall away; (a ship) runs aground' where lemma = 'ἐκπίπτω'
update dictionary set gloss = 'a young man' where lemma = 'νεανίας'
update dictionary set gloss = 'I deliberate; I meet together' where lemma = 'συμβάλλω'
update dictionary set gloss = 'I endure' where lemma = 'στέγω'
update dictionary set gloss = 'freely, wothout cost; without purpose' where lemma = 'δωρεάν'
update dictionary set gloss = 'I look carefully; I pay attention' where lemma = 'σκοπέω'
update dictionary set gloss = 'I overthrow, destroy; I find lodging' where lemma = 'καταλύω'
update dictionary set gloss = 'a sword' where lemma = 'ῥομφαία'
update dictionary set gloss = 'I put aside, put away' where lemma = 'ἀποτίθημι'
update dictionary set gloss = 'lest (ever), lest (at any time)' where lemma = 'μήποτε'
update dictionary set gloss = 'I inherit, obtain (by inheritance)' where lemma = 'κληρονομέω'
update dictionary set gloss = 'fire (metaph - trials)' where lemma = 'πῦρ'
update dictionary set gloss = 'I am very enthusiastic (lit. I burn)' where lemma = 'ζέω'
update dictionary set gloss = 'I provide; I cause' where lemma = 'παρέχω'
update dictionary set gloss = 'I follow closely' where lemma = 'ἐπακολουθέω'
update dictionary set gloss = 'sufficient, enough' where lemma = 'ἀρκετός'
update dictionary set gloss = 'I prosper' where lemma = 'εὐοδόω'
update dictionary set gloss = 'a whip, a lash (metph - suffering)' where lemma = 'μάστιξ'
update dictionary set gloss = 'hard, harsh' where lemma = 'σκληρός'
update dictionary set gloss = 'I rent out for hire' where lemma = 'ἐκδίδωμι'
update dictionary set gloss = 'I am placed around; I am surrounded' where lemma = 'περίκειμαι'

update verbparts set parts = 'ἀφαιρέω, ἀφελῶ, ἀφεῖλον, -, -, ἀφῃρέθην' where lemma = 'ἀφαιρέω'
